ALTER TABLE paper_orders ADD COLUMN IF NOT EXISTS filled_quantity NUMERIC(28, 8) DEFAULT 0 NOT NULL;
ALTER TABLE paper_orders ADD COLUMN IF NOT EXISTS average_fill_price NUMERIC(28, 8) DEFAULT 0 NOT NULL;
ALTER TABLE paper_orders ADD COLUMN IF NOT EXISTS fee_paid NUMERIC(28, 8) DEFAULT 0 NOT NULL;

ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS unrealized_pnl NUMERIC(28, 8) DEFAULT 0 NOT NULL;
ALTER TABLE paper_positions ADD COLUMN IF NOT EXISTS state VARCHAR(20) DEFAULT 'Open' NOT NULL;
